Vagrant.configure("2") do |config|
  config.vm.define "ubuntu" do |ubuntu|
    centos.vm.box = "ubuntu"
    config.vm.provision "shell" do |s|
      s.inline = " 
      touch shahub
      apt-get update
      apt-get install -y apache2"
    centos.vm.network "forwarded_post", guest: 80, host: 8080
   end
end 
